### PR TITLE
Remove profile

### PR DESCRIPTION
**Pull request by gforcada**
According to https://github.com/plone/plone.app.folder/issues/2
the profile is not needed anymore.

### CODE REVIEW

**Comment by jensens** [comment]
Great! And ``alltests --all`` are running?

**Comment by gforcada** [comment]
Will run that one, just wait... a few hours :)

**Comment by gforcada** [comment]
I got some robot framework tests and some p.a.event errors also, although without my changes the errors happen also anyway...

**Comment by jensens** [comment]
I know this pain. Getting testing all up and  running on a dev box is a mission on its own. 

While preparing merge i stumbled over another question: master of this package is used in both, coredev 4 and 5 - is it save to merg for 4 too, or do we need to branch away a 1.x branch and let coredev 5 use master with a 2.0 version?

**Comment by gforcada** [comment]
Not a problem for me, but surely for the average contributor...

About your question, @esteele maybe has more insight, still branching away will keep us on the safe side (although with some extra work to be done :)

**Comment by jensens** [comment]
I dont see anything using the profile of plone.app.folder. Its dead code in Plone 4+ In paf 1.1 I already removed other Plone 3 related stuff, so its imo save to remove the profile too. So: merge is fine.

Just one little thing: Please add a short change-log entry.

**Comment by gforcada** [comment]
@jensens will do, thanks for the archaeology!

**Pull request merged**
